/* Generated by AN DISI Unibo */ 
package it.unibo.fanautomatizer

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Fanautomatizer ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		var fanIsStarted=0
			var minTemp=20
			var maxTemp=40 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("fanautomatizer | start")
					}
					 transition( edgeName="goto",targetState="monitoring", cond=doswitch() )
				}	 
				state("monitoring") { //this:State
					action { //it:State
						println("fanautomatizer monitoring the situation | fanautomatizer")
					}
					 transition(edgeName="t050",targetState="handleTemp",cond=whenEvent("temperature"))
				}	 
				state("handleTemp") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("temperature(T)"), Term.createTerm("temperature(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var temp=payloadArg(0).toInt()
											if(  temp >= maxTemp  && fanIsStarted == 0){
													println("fanautomatizer [handleTemp]: send start command to fan  | fanautomatizer")
													forward("startfan", "startfan(on)" ,"fan" )
													fanIsStarted = 1
											}
											if(temp <= minTemp  && fanIsStarted == 1 ){
												println("fanautomatizer [handleTemp]: send stop command to fan | fanautomatizer")
												forward("stopfan", "stopfan(off)" ,"fan" )
												fanIsStarted = 0
												}	  
						}
					}
					 transition(edgeName="t051",targetState="handleTemp",cond=whenEvent("temperature"))
				}	 
			}
		}
}
