/* Generated by AN DISI Unibo */ 
package it.unibo.trolleystopper

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Trolleystopper ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
					}
					 transition(edgeName="t050",targetState="stopped",cond=whenDispatch("stopTrolley"))
				}	 
				state("stopped") { //this:State
					action { //it:State
						forward("trolleystop", "trolleystop(manager)" ,"trolley" ) 
					}
					 transition(edgeName="t051",targetState="resumed",cond=whenDispatch("resumeTrolley"))
				}	 
				state("resumed") { //this:State
					action { //it:State
						forward("trolleyresume", "trolleyresume(manager)" ,"trolley" ) 
					}
				}	 
			}
		}
}
